name: Enviar Top 3 Salão JP

on:
  schedule:
    - cron: '0 11 * * 1'        # Toda segunda-feira às 08:00 BRT
  workflow_dispatch:
  repository_dispatch:
    types: [top3_update]        # <<< permite disparo via API

concurrency:
  group: top3
  cancel-in-progress: true

jobs:
  run-top3:
    runs-on: ubuntu-latest
    env:
      TZ: America/Sao_Paulo
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install gspread gspread-dataframe google-auth pandas pytz requests
      - name: Run
        run: python top_3_salao_JP.py
